In [1]:
import numpy as np

### set seed

In [2]:
np.random.seed(123)

### set random state which is independent from the global seed

In [3]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### generate a random sample from interval [0, 1) in a given shape

In [4]:
# generate a random scalar
print(np.random.rand())      

0.6964691855978616


In [5]:
# generate a 1-D array
print(np.random.rand(3))           

[0.28613933 0.22685145 0.55131477]


In [6]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.71946897 0.42310646 0.9807642 ]
 [0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [7]:
print(np.random.randn(3,3))

[[-0.14337247 -0.6191909  -0.76943347]
 [ 0.57674602  0.12652592 -1.30148897]
 [ 2.20742744  0.52274247  0.46564476]]


### generate an array of random integers in a given interval [low, high)

In [8]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[5 7 2]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [9]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.65472131 0.37380143 0.23451288 0.98799529 0.76599595 0.77700444
 0.02798196 0.17390652 0.15408224 0.07708648]
[0.8898657  0.7503787  0.69340324 0.51176338 0.46426806 0.56843069
 0.30254945 0.49730879 0.68326291 0.91669867]
[0.10892895 0.49549179 0.23283593 0.43686066 0.75154299 0.48089213
 0.79772841 0.28270293 0.43341824 0.00975735]
[0.34079598 0.68927201 0.86936929 0.26780382 0.45674792 0.26828131
 0.8370528  0.27051466 0.53006201 0.17537266]


### generate a random sample from a given 1-D array

In [10]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[1 1 1 1 1 1 1 2 2 1]


In [11]:
print(np.random.choice(3, 10))

[1 0 1 2 2 0 1 1 1 0]


In [12]:
print(np.random.choice([1,2,3], 10))

[2 2 1 3 2 3 1 2 1 3]


### shuffle an array in place

In [13]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
np.random.shuffle(arr)
print(arr)

[1 2 8 5 4 0 6 7 9 3]


### generate a permutation of an array

In [15]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [3 6 2 4 5 9 1 8 0 7]
