In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)

### sort an array along a specified axis

In [3]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[0.32367677 0.160538   0.07577069 0.02051216 0.23410999]
 [0.54927129 0.20910696 0.2196075  0.22756129 0.67417506]
 [0.63553217 0.56279363 0.62776371 0.32657277 0.79901529]
 [0.7183594  0.69288395 0.70838123 0.52581954 0.96520237]
 [0.81701677 0.79908087 0.98800108 0.54773388 0.97694313]]


In [4]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.32367677 0.160538   0.07577069 0.02051216 0.23410999]
 [0.54927129 0.20910696 0.2196075  0.22756129 0.67417506]
 [0.63553217 0.56279363 0.62776371 0.32657277 0.79901529]
 [0.7183594  0.69288395 0.70838123 0.52581954 0.96520237]
 [0.81701677 0.79908087 0.98800108 0.54773388 0.97694313]]


In [5]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.02051216 0.07577069 0.160538   0.23410999 0.32367677]
 [0.20910696 0.2196075  0.22756129 0.54927129 0.67417506]
 [0.32657277 0.56279363 0.62776371 0.63553217 0.79901529]
 [0.52581954 0.69288395 0.70838123 0.7183594  0.96520237]
 [0.54773388 0.79908087 0.81701677 0.97694313 0.98800108]]


In [6]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.02051216 0.07577069 0.160538   0.23410999 0.32367677]
 [0.20910696 0.2196075  0.22756129 0.54927129 0.67417506]
 [0.32657277 0.56279363 0.62776371 0.63553217 0.79901529]
 [0.52581954 0.69288395 0.70838123 0.7183594  0.96520237]
 [0.54773388 0.79908087 0.81701677 0.97694313 0.98800108]]


### compute the indices that would sort an array along a specified axis

In [7]:
arr = np.random.rand(5,5)

In [8]:
# along the row
print(np.argsort(arr, axis=0))

[[1 1 2 2 0]
 [2 2 1 3 2]
 [0 4 0 1 4]
 [4 3 3 0 3]
 [3 0 4 4 1]]


In [9]:
# along the column
print(np.argsort(arr, axis=1))

[[4 3 2 0 1]
 [0 3 1 2 4]
 [3 2 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


In [10]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[13 12  5 18  4  8  6  7 14  3 10 24  2 11  0 19 20 21  9 15 16 17 22  1
 23]
