In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

### ```np.concatenate((a, b), axis=0)```

In [3]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [4]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [5]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [6]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [7]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [8]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [9]:
arr = np.random.rand(6,6)

In [10]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[1.85084671e-01, 8.19931716e-01, 1.88785472e-01, 7.32790656e-01,
        2.32967008e-01, 4.27668094e-01],
       [3.36885470e-01, 1.69041396e-01, 3.00931103e-01, 3.34405185e-01,
        9.33827335e-05, 3.62887755e-01],
       [3.88854091e-01, 3.62926147e-02, 2.89134857e-01, 4.08424369e-02,
        4.54621961e-01, 6.10321623e-02]]), array([[0.02005274, 0.48136698, 0.61415211, 0.72337006, 0.901569  ,
        0.4099042 ],
       [0.0788683 , 0.0391728 , 0.7366417 , 0.16636387, 0.81541604,
        0.50994101],
       [0.03721661, 0.52077208, 0.57089404, 0.30703524, 0.86827655,
        0.03858626]])]


In [11]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.18508467, 0.81993172, 0.18878547],
       [0.33688547, 0.1690414 , 0.3009311 ],
       [0.38885409, 0.03629261, 0.28913486],
       [0.02005274, 0.48136698, 0.61415211],
       [0.0788683 , 0.0391728 , 0.7366417 ],
       [0.03721661, 0.52077208, 0.57089404]]), array([[7.32790656e-01, 2.32967008e-01, 4.27668094e-01],
       [3.34405185e-01, 9.33827335e-05, 3.62887755e-01],
       [4.08424369e-02, 4.54621961e-01, 6.10321623e-02],
       [7.23370058e-01, 9.01568997e-01, 4.09904205e-01],
       [1.66363873e-01, 8.15416042e-01, 5.09941012e-01],
       [3.07035238e-01, 8.68276552e-01, 3.85862638e-02]])]
